### ISSUE TITLE
Unable to locate a modulefile for 'blic-modules'

### ISSUE THREAD

**Issue by gurpreet-bioinfo** [UCL-BLIC/merge_fastq#1]
Hi @lconde-ucl ,

I have been using Nextflow RNA-seq pipeline before, so I already have Nextflow working but first time I tried to use nextflow merge_fastq (instead of using bash script). While following [https://github.com/UCL-BLIC/merge_fastq/blob/master/docs/usage.md](url), I ran:
```
`$ module load blic-modules`
```
and got following error:
```
ModuleCmd_Load.c(208):ERROR:105: Unable to locate a modulefile for 'blic-modules'
```

Please help if I missed anything.

Thanks.
Gurpreet

**Comment by lconde-ucl** [comment]
Hi Gurpreet,

sorry the repository is public but was only meant to work within our clusters (`module load blic-modules nextflow` loads all the software including nextflow that the pipeline needs). But if you look at the main.ng script you will see that the pipeline simply runs a process:

`merge_and_rename_NGI_fastq_files.py $inputdir ./ > merge_log`

So you could just download the above python script from the /bin folder and run it in your computer.
Hope this helps,
Best,
Lucia

**Comment by gurpreet-bioinfo** [comment]
Thanks @lconde-ucl .
